// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9CqP1aK6ZpeiWVWRtx8AHxq7HWtWK2o',
    appId: '1:997442967845:web:97796b42116ddde5e662cc',
    messagingSenderId: '997442967845',
    projectId: 'laptrinhmobile-1e616',
    authDomain: 'laptrinhmobile-1e616.firebaseapp.com',
    storageBucket: 'laptrinhmobile-1e616.firebasestorage.app',
    measurementId: 'G-8W7MMYXWTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhvwPmY3prK3Cg1JzKx8PLBcyUvH00As',
    appId: '1:997442967845:android:e1d942d1c31870a9e662cc',
    messagingSenderId: '997442967845',
    projectId: 'laptrinhmobile-1e616',
    storageBucket: 'laptrinhmobile-1e616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAihGoIGFh1dqLDopcMi-F_r-hFANCBusw',
    appId: '1:997442967845:ios:44ed74f78c532b3fe662cc',
    messagingSenderId: '997442967845',
    projectId: 'laptrinhmobile-1e616',
    storageBucket: 'laptrinhmobile-1e616.firebasestorage.app',
    iosBundleId: 'com.example.quanlythietbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAihGoIGFh1dqLDopcMi-F_r-hFANCBusw',
    appId: '1:997442967845:ios:44ed74f78c532b3fe662cc',
    messagingSenderId: '997442967845',
    projectId: 'laptrinhmobile-1e616',
    storageBucket: 'laptrinhmobile-1e616.firebasestorage.app',
    iosBundleId: 'com.example.quanlythietbi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy9CqP1aK6ZpeiWVWRtx8AHxq7HWtWK2o',
    appId: '1:997442967845:web:b6b35dd461c29ea7e662cc',
    messagingSenderId: '997442967845',
    projectId: 'laptrinhmobile-1e616',
    authDomain: 'laptrinhmobile-1e616.firebaseapp.com',
    storageBucket: 'laptrinhmobile-1e616.firebasestorage.app',
    measurementId: 'G-X4NVGMC9HJ',
  );
}
